### ISSUE TITLE
HttpExceptions causing PHP warning

### ISSUE THREAD

**Issue by stadskle** [BanxaOfficial/php-sdk#10]
During a GET order call the SDK are issuing warnings on httpExceptions (seems like it is a 400):

```
PHP Warning:  Undefined array key "code" in /var/task/vendor/banxa/php-sdk/src/Exceptions/HttpException.php on line 88
PHP Warning:  Undefined array key "title" in /var/task/vendor/banxa/php-sdk/src/Exceptions/HttpException.php on line 88
```

I am running PHP 8.2 and have the latest SDK.

The source of the issue is here:

```php
            return array_key_exists('errors', $decoded)
                ? $decoded['errors']['title'] . ' (Code: ' . $decoded['errors']['code'] . ')'
                : $contents;
```

So it seems like $decoded can return errors with not title/code.

**Comment by WesleyVroegh** [comment]
Hi [stadskle](https://github.com/stadskle),
Thank you for raising this issue.

We have added this to our todo list to be resolved.

**Comment by AlexBanxa** [comment]
Closing as fixed in latest release @stadskle
